### ISSUE TITLE
zsh: command not found: colorls

### ISSUE THREAD

**Issue by dylanjm** [athityakumar/colorls#264]
### Description

After running `gem install colorls` I get this message:

```
 *******************************************************************
    Changes introduced in colorls

    Sort by dirs  : -sd flag has been renamed to --sd
    Sort by files : -sf flag has been renamed to --sf
    Git status    : -gs flag has been renamed to --gs

    Clubbed flags : `colorls -ald` works
    Help menu     : `colorls -h` provides all possible flag options

    Tab completion enabled for flags

    -t flag : Previously short for --tree, has been re-allocated to sort results by time
    -r flag : Previously short for --report, has been re-allocated to reverse sort results

    Man pages have been added. Checkout `man colorls`.

  *******************************************************************
Successfully installed colorls-1.1.1
Parsing documentation for colorls-1.1.1
Done installing documentation for colorls after 0 seconds
1 gem installed
```

Which looks fine and dandy but when I try to run something like `colorls -lA` I get

```
zsh: command not found: colorls
```

`which ruby`: /usr/local/opt/ruby/bin/ruby
`ruby --version`: ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ X] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by danaguilar** [comment]
I think you need to add the following to your `~/.zshrc` file.

`source $(dirname $(gem which colorls))/tab_complete.sh`

Then reload zsh either by restarting it or using `source ~/.zshrc`

**Comment by dylanjm** [comment]
I have done that already and it's still not working

**Comment by avdv** [comment]
> `source $(dirname $(gem which colorls))/tab_complete.sh`

That is only loading the completions support.

In order to run commands from installed Ruby gems, you need to add the bin path of your gem folder to the PATH.

For Zsh:
```
path+=(
    $(ruby -e 'puts File.join(Gem.user_dir, "bin")')
)
```

**Comment by ivy00johns** [comment]
I'm experiencing the same issue currently.

**Comment by avdv** [comment]
@ivy00johns try this:
```
$(ruby -e 'puts File.join(Gem.user_dir, "bin")')/colorls
```
Does that work?

As I said, you need to ensure that colorls is found in the PATH, wherever you installed it. (globally? in your user dir?)

Note that you need to re-install colorls when you upgraded Ruby.

**Comment by aimuch** [comment]
I install Ruby by    
```shell
brew install brew
```

<img width="650" alt="colorls-error" src="https://user-images.githubusercontent.com/17581911/53730296-7d5f2900-3eb2-11e9-971d-4e5de58fdb4d.png">

**Comment by avdv** [comment]
@aimuch as I already said, you need to ensure your shell is able to find the colorls script. You should add the `Gem.bindir` directory to your `PATH` environment variable in order to run scripts from *any* installed gem.

Look at the output of `gem environment`. The directory mentioned in `EXECUTABLE DIRECTORY` should be also listed in `SHELL PATH`.

Add this to your shell init file:
```
PATH=$PATH:$(ruby -e 'puts Gem.bindir')
```

**Comment by aimuch** [comment]
> @aimuch as I already said, you need to ensure your shell is able to find the colorls script. You should add the `Gem.bindir` directory to your `PATH` environment variable in order to run scripts from _any_ installed gem.
> 
> Look at the output of `gem environment`. The directory mentioned in `EXECUTABLE DIRECTORY` should be also listed in `SHELL PATH`.
> 
> Add this to your shell init file:
> 
> ```
> PATH=$PATH:$(ruby -e 'puts Gem.bindir')
> ```

Thank you, my fault

**Comment by Who23** [comment]
For me, I fixed this issue by uncommenting a line I had commented out:
`eval "$(rbenv init -)"`

I don't know if you already have this but hope it helps.

**Comment by avdv** [comment]
> For me, I fixed this issue by uncommenting a line I had commented out:
> `eval "$(rbenv init -)"`
> 
> I don't know if you already have this but hope it helps.

Of course, if you use rbenv, RVM, chruby or similar managers, you have to make sure to configure them correctly before colorls will work.

@dylanjm are you still having the issue?

**Comment by avdv** [comment]
Closing, since there's nothing left to do and OP lost interest, apparently.

**Comment by Aisuko** [comment]
> @aimuch as I already said, you need to ensure your shell is able to find the colorls script. You should add the `Gem.bindir` directory to your `PATH` environment variable in order to run scripts from _any_ installed gem.
> 
> Look at the output of `gem environment`. The directory mentioned in `EXECUTABLE DIRECTORY` should be also listed in `SHELL PATH`.
> 
> Add this to your shell init file:
> 
> ```
> PATH=$PATH:$(ruby -e 'puts Gem.bindir')
> ```

Thanks for your reply, but the script did not work for me(Every time open a new session, it need to `source ~/.zshrc to reload colorls` ). So, I have been changed it to 

```
PATH=$PATH:/usr/local/lib/ruby/gems/2.6.0/bin
```

**Comment by chanw9** [comment]
> > @aimuch as I already said, you need to ensure your shell is able to find the colorls script. You should add the `Gem.bindir` directory to your `PATH` environment variable in order to run scripts from _any_ installed gem.
> > Look at the output of `gem environment`. The directory mentioned in `EXECUTABLE DIRECTORY` should be also listed in `SHELL PATH`.
> > Add this to your shell init file:
> > ```
> > PATH=$PATH:$(ruby -e 'puts Gem.bindir')
> > ```
> 
> Thanks for your reply, but the script did not work for me(Every time open a new session, it need to `source ~/.zshrc to reload colorls` ). So, I have been changed it to
> 
> ```
> echo $(ruby -e 'puts Gem.bindir')
> /usr/local/lib/ruby/gems/2.6.0/bin
> 
> PATH=$PATH:/usr/local/lib/ruby/gems/2.6.0/bin
> ```

Same problem.
fixed with
`PATH=$(ruby -e 'puts Gem.bindir'):$PATH`

**Comment by Vadorequest** [comment]
This happened to me after upgrading MacOS to Catalina. Didn't try any fix so far, don't like to mess up with gems/ruby.

**Comment by SmithJson** [comment]
> @aimuch as I already said, you need to ensure your shell is able to find the colorls script. You should add the `Gem.bindir` directory to your `PATH` environment variable in order to run scripts from _any_ installed gem.
> 
> Look at the output of `gem environment`. The directory mentioned in `EXECUTABLE DIRECTORY` should be also listed in `SHELL PATH`.
> 
> Add this to your shell init file:
> 
> ```
> PATH=$PATH:$(ruby -e 'puts Gem.bindir')
> ```

Thanks，I solved this problem

**Comment by BNK-ALONG** [comment]
> @aimuch as I already said, you need to ensure your shell is able to find the colorls script. You should add the `Gem.bindir` directory to your `PATH` environment variable in order to run scripts from _any_ installed gem.
> 
> Look at the output of `gem environment`. The directory mentioned in `EXECUTABLE DIRECTORY` should be also listed in `SHELL PATH`.
> 
> Add this to your shell init file:
> 
> ```
> PATH=$PATH:$(ruby -e 'puts Gem.bindir')
> ```

Thanks,I solved this problem.This is my solution.
Edit `~/.zshrc` and add the following line:
`export PATH=$PATH:$(ruby -e 'puts Gem.bindir')`
Then,`source ~/.zshrc` and colorls can work.

**Comment by Rallanvila** [comment]
> @aimuch as I already said, you need to ensure your shell is able to find the colorls script. You should add the `Gem.bindir` directory to your `PATH` environment variable in order to run scripts from _any_ installed gem.
> 
> Look at the output of `gem environment`. The directory mentioned in `EXECUTABLE DIRECTORY` should be also listed in `SHELL PATH`.
> 
> Add this to your shell init file:
> 
> ```
> PATH=$PATH:$(ruby -e 'puts Gem.bindir')
> ```

i've added this to my .zshrc file however i'm still getting 
`zsh: command not found: ' colorls`

It seems like everybody has a fix however it isn't working for me . I'm on an M1

**Comment by avdv** [comment]
> > @aimuch as I already said, you need to ensure your shell is able to find the colorls script. You should add the `Gem.bindir` directory to your `PATH` environment variable in order to run scripts from _any_ installed gem.
> > Look at the output of `gem environment`. The directory mentioned in `EXECUTABLE DIRECTORY` should be also listed in `SHELL PATH`.
> > Add this to your shell init file:
> > ```
> > PATH=$PATH:$(ruby -e 'puts Gem.bindir')
> > ```
> 
> i've added this to my .zshrc file however i'm still getting
> `zsh: command not found: ' colorls`

That looks fishy. Is this the real output?
 
> It seems like everybody has a fix however it isn't working for me . I'm on an M1

You have to ensure that you run all Ruby related commands in x86 mode, ie. prefix any Ruby script with `arch -x86_64`.

**Comment by md-siam** [comment]
Copy this path to: .zshrc
```
export PATH=$PATH:$(ruby -e 'puts Gem.bindir')
```

**Comment by ajmalmohammedn** [comment]
> @aimuch as I already said, you need to ensure your shell is able to find the colorls script. You should add the `Gem.bindir` directory to your `PATH` environment variable in order to run scripts from _any_ installed gem.
> 
> Look at the output of `gem environment`. The directory mentioned in `EXECUTABLE DIRECTORY` should be also listed in `SHELL PATH`.
> 
> Add this to your shell init file:
> 
> ```
> PATH=$PATH:$(ruby -e 'puts Gem.bindir')
> ```

this one works fine try it

**Comment by rioyuda02** [comment]
> PATH=$(ruby -e 'puts Gem.bindir'):$PATH

I solved with this command
